---
- name: Test Connection
  hosts: production
  become: yes

  vars:
    source: '/var/www/symfony4/ansible/index.html'
    destination: '/var/www/html'
    message1: 'Hello'
    message2: 'World'

  tasks:
    - name: Check the name of distribution
      debug: var=ansible_os_family

    - block: # ==== Block for Debian ==== #
        - name: Install python2
          raw: sudo apt install -y python-minimal
          become: true

        - name: Install aptitude
          apt:
            name: aptitude
            state: present
          become: true

        - name: Update all packages
          apt:
            update_cache: yes
            upgrade: safe
            autoremove: yes
          become: true

        - name: Install Apache Web Server
          when: ansible_os_family == 'Debian'
          apt:
            name: apache2
            state: latest

        - name: Start Apache and Enable
          service: name=apache2 state=started enabled=yes

      when: ansible_os_family == 'Debian'

    - block: # ==== Block for Debian ==== #
        - name: Install Apache for RedHat
          yum: name=httpd state=latest

        - name: Start Apache and Enable
          service: name=httpd state=started enabled=yes
      when: ansible_os_family == 'RedHat'

    - name: Create project directory and set its permissions
      file:
        path: "/var/www/html"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes

    - name: Copy project
      copy: src={{ source }} dest={{ destination }} mode=0555
      notify: Restart Apache Ubuntu

    - name: Clone repo
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/appuser/reddit

    - name: Print vars
      debug:
        var: message1

    - name: Say hello to all
      debug: msg='hello {{ item }}'
      loop:
        - 'Vasya'
        - 'Petya'
        - 'Masha'
        - 'Olya'

    - name: loop until example
      shell: echo -n Z >> myfile.txt && cat myfile.txt
      register: output
      delay: 2
      retries: 10
      until: output.stdout.find('ZZZZ') == false

    - name: print optput
      debug:
        var: output.stdout

    - name: install many packages
      yum: name={{item}} state=latest
      loop:
        - python
        - tree

  handlers:
    - name: Restart Apache Ubuntu
      service: name=apache2 state=restarted

    - name: Restart Apache RedHat
      service: name=httpd state=restarted