---
- name: "Ansible playbook example"
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  tasks:
    - name: Install Apache Web Server
      apt:
        name: apache2
        state: latest

    - name: Install python2
      raw: apt install -y python-minimal
      become: true

    - name: Create project directory and set its permissions
      file:
        path: "/var/www/ansible-local"
        state: directory
        owner: "user"
        group: "user"
        recurse: yes

    - name: Checkout Git repository
      register: repo_code
      git:
        repo: https://github.com/Ilya91/Symfony4.git
        dest: "/var/www/ansible-local"
        force: yes